name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: 检出代码
        uses: actions/checkout@v5

      - name: 设置 Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-cov respx
          pip install fastmcp httpx pydantic-settings ruff

      - name: 运行测试
        run: |
          pytest tests/ -v --cov=src --cov-report=xml --cov-report=term-missing

      - name: 上传覆盖率报告
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: 代码质量检查
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v5

      - name: 设置 Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: 安装 ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Ruff 格式检查
        run: ruff format --check src/ tests/

      - name: Ruff 代码检查
        run: ruff check src/ tests/

  validate:
    name: 验证服务器配置
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v5

      - name: 设置 Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install fastmcp httpx pydantic-settings

      - name: 验证服务器
        run: python validate_server.py
