name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    name: 构建分发包
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v5

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装构建工具
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: 构建包
        run: python -m build

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  # 取消注释以下内容以启用 PyPI 发布
  # publish-pypi:
  #   name: 发布到 PyPI
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/yapi-mcp
  #   permissions:
  #     id-token: write
  #
  #   steps:
  #     - name: 下载构建产物
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: dist
  #         path: dist/
  #
  #     - name: 发布到 PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
